# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connectorCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import connector_pb2 as connector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='connectorCommand.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'\n\034com.ditrit.gandalf.java.grpcB\025ConnectorCommandProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63onnectorCommand.proto\x12\x04grpc\x1a\x0f\x63onnector.proto\"\xff\x02\n\x0e\x43ommandMessage\x12\x18\n\x10SourceAggregator\x18\x01 \x01(\t\x12\x17\n\x0fSourceConnector\x18\x02 \x01(\t\x12\x14\n\x0cSourceWorker\x18\x03 \x01(\t\x12\x1d\n\x15\x44\x65stinationAggregator\x18\x04 \x01(\t\x12\x1c\n\x14\x44\x65stinationConnector\x18\x05 \x01(\t\x12\x19\n\x11\x44\x65stinationWorker\x18\x06 \x01(\t\x12\x0e\n\x06Tenant\x18\x07 \x01(\t\x12\r\n\x05Token\x18\x08 \x01(\t\x12\x0f\n\x07\x43ontext\x18\t \x01(\t\x12\x0f\n\x07Timeout\x18\n \x01(\t\x12\x11\n\tTimestamp\x18\x0b \x01(\t\x12\r\n\x05Major\x18\x0c \x01(\x03\x12\r\n\x05Minor\x18\r \x01(\x03\x12\x0c\n\x04UUID\x18\x0e \x01(\t\x12\x15\n\rConnectorType\x18\x0f \x01(\t\x12\x13\n\x0b\x43ommandType\x18\x10 \x01(\t\x12\x0f\n\x07\x43ommand\x18\x11 \x01(\t\x12\x0f\n\x07Payload\x18\x12 \x01(\t\"\"\n\x12\x43ommandMessageUUID\x12\x0c\n\x04UUID\x18\x01 \x01(\t\"\\\n\x12\x43ommandMessageWait\x12\x14\n\x0cWorkerSource\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\x12\x12\n\nIteratorId\x18\x03 \x01(\t\x12\r\n\x05Major\x18\x04 \x01(\x03\x32\xe1\x01\n\x10\x43onnectorCommand\x12\x46\n\x12SendCommandMessage\x12\x14.grpc.CommandMessage\x1a\x18.grpc.CommandMessageUUID\"\x00\x12\x46\n\x12WaitCommandMessage\x12\x18.grpc.CommandMessageWait\x1a\x14.grpc.CommandMessage\"\x00\x12=\n\x15\x43reateIteratorCommand\x12\x0b.grpc.Empty\x1a\x15.grpc.IteratorMessage\"\x00\x42\x37\n\x1c\x63om.ditrit.gandalf.java.grpcB\x15\x43onnectorCommandProtoP\x01\x62\x06proto3'
  ,
  dependencies=[connector__pb2.DESCRIPTOR,])




_COMMANDMESSAGE = _descriptor.Descriptor(
  name='CommandMessage',
  full_name='grpc.CommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SourceAggregator', full_name='grpc.CommandMessage.SourceAggregator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SourceConnector', full_name='grpc.CommandMessage.SourceConnector', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SourceWorker', full_name='grpc.CommandMessage.SourceWorker', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DestinationAggregator', full_name='grpc.CommandMessage.DestinationAggregator', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DestinationConnector', full_name='grpc.CommandMessage.DestinationConnector', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DestinationWorker', full_name='grpc.CommandMessage.DestinationWorker', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Tenant', full_name='grpc.CommandMessage.Tenant', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Token', full_name='grpc.CommandMessage.Token', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Context', full_name='grpc.CommandMessage.Context', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Timeout', full_name='grpc.CommandMessage.Timeout', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='grpc.CommandMessage.Timestamp', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Major', full_name='grpc.CommandMessage.Major', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Minor', full_name='grpc.CommandMessage.Minor', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UUID', full_name='grpc.CommandMessage.UUID', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ConnectorType', full_name='grpc.CommandMessage.ConnectorType', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CommandType', full_name='grpc.CommandMessage.CommandType', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Command', full_name='grpc.CommandMessage.Command', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='grpc.CommandMessage.Payload', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=433,
)


_COMMANDMESSAGEUUID = _descriptor.Descriptor(
  name='CommandMessageUUID',
  full_name='grpc.CommandMessageUUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UUID', full_name='grpc.CommandMessageUUID.UUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=469,
)


_COMMANDMESSAGEWAIT = _descriptor.Descriptor(
  name='CommandMessageWait',
  full_name='grpc.CommandMessageWait',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='WorkerSource', full_name='grpc.CommandMessageWait.WorkerSource', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Value', full_name='grpc.CommandMessageWait.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IteratorId', full_name='grpc.CommandMessageWait.IteratorId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Major', full_name='grpc.CommandMessageWait.Major', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=563,
)

DESCRIPTOR.message_types_by_name['CommandMessage'] = _COMMANDMESSAGE
DESCRIPTOR.message_types_by_name['CommandMessageUUID'] = _COMMANDMESSAGEUUID
DESCRIPTOR.message_types_by_name['CommandMessageWait'] = _COMMANDMESSAGEWAIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandMessage = _reflection.GeneratedProtocolMessageType('CommandMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDMESSAGE,
  '__module__' : 'connectorCommand_pb2'
  # @@protoc_insertion_point(class_scope:grpc.CommandMessage)
  })
_sym_db.RegisterMessage(CommandMessage)

CommandMessageUUID = _reflection.GeneratedProtocolMessageType('CommandMessageUUID', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDMESSAGEUUID,
  '__module__' : 'connectorCommand_pb2'
  # @@protoc_insertion_point(class_scope:grpc.CommandMessageUUID)
  })
_sym_db.RegisterMessage(CommandMessageUUID)

CommandMessageWait = _reflection.GeneratedProtocolMessageType('CommandMessageWait', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDMESSAGEWAIT,
  '__module__' : 'connectorCommand_pb2'
  # @@protoc_insertion_point(class_scope:grpc.CommandMessageWait)
  })
_sym_db.RegisterMessage(CommandMessageWait)


DESCRIPTOR._options = None

_CONNECTORCOMMAND = _descriptor.ServiceDescriptor(
  name='ConnectorCommand',
  full_name='grpc.ConnectorCommand',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=566,
  serialized_end=791,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendCommandMessage',
    full_name='grpc.ConnectorCommand.SendCommandMessage',
    index=0,
    containing_service=None,
    input_type=_COMMANDMESSAGE,
    output_type=_COMMANDMESSAGEUUID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WaitCommandMessage',
    full_name='grpc.ConnectorCommand.WaitCommandMessage',
    index=1,
    containing_service=None,
    input_type=_COMMANDMESSAGEWAIT,
    output_type=_COMMANDMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateIteratorCommand',
    full_name='grpc.ConnectorCommand.CreateIteratorCommand',
    index=2,
    containing_service=None,
    input_type=connector__pb2._EMPTY,
    output_type=connector__pb2._ITERATORMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTORCOMMAND)

DESCRIPTOR.services_by_name['ConnectorCommand'] = _CONNECTORCOMMAND

# @@protoc_insertion_point(module_scope)
