model:
name: PythonDemoConnectorConfig_1

# Product Type
connectorproduct:
  name: Demo
  version: 1

# Commands
connectorcommands:
- model:
  name: RUN_TEST_1
  schema: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/RunTest1",
    "definitions": {
      "RunTest1": {
        "required": [],
        "properties": {
          "TestValue1": {
            "type": "string",
          }
        },
        "additionalProperties": false,
        "type": "object"
      }
    }
  }'
  actions:
    - model:
      name: runTest1
- model:
  name: RUN_TEST_2
  schema: '{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "#/definitions/RunTest2",
    "definitions": {
      "RunTest1": {
        "required": [],
        "properties": {
          "TestValue2": {
            "type": "string",
          }
        },
        "additionalProperties": false,
        "type": "object"
      }
    }
  }'
  actions:
    - model:
      name: runTest2
# Events
# - model:
#   name: RUN_TEST_2
#   schema: '{
#     "type": "string"  
#   }'
#   actions:
#     - model:
#       name: runTest

# Resources
# resources:
# - model:
#   name: test_resource_1
#   actions:
#     - model:
#       name: create
#     - model:
#       name: read
#     - model:
#       name: update
#     - model:
#       name: delete