# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connector.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'\n\034com.ditrit.gandalf.java.grpcB\016ConnectorProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63onnector.proto\x12\x04grpc\"=\n\x0b\x43ommandList\x12\r\n\x05Major\x18\x01 \x01(\x03\x12\r\n\x05Minor\x18\x02 \x01(\x03\x12\x10\n\x08\x43ommands\x18\x03 \x03(\t\"\x19\n\x08Validate\x12\r\n\x05valid\x18\x01 \x01(\x08\"$\n\x04Stop\x12\r\n\x05Major\x18\x01 \x01(\x03\x12\r\n\x05Minor\x18\x02 \x01(\x03\"\x07\n\x05\x45mpty\"\x1d\n\x0fIteratorMessage\x12\n\n\x02Id\x18\x01 \x01(\t2m\n\tConnector\x12\x36\n\x0fSendCommandList\x12\x11.grpc.CommandList\x1a\x0e.grpc.Validate\"\x00\x12(\n\x08SendStop\x12\n.grpc.Stop\x1a\x0e.grpc.Validate\"\x00\x42\x30\n\x1c\x63om.ditrit.gandalf.java.grpcB\x0e\x43onnectorProtoP\x01\x62\x06proto3'
)




_COMMANDLIST = _descriptor.Descriptor(
  name='CommandList',
  full_name='grpc.CommandList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Major', full_name='grpc.CommandList.Major', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Minor', full_name='grpc.CommandList.Minor', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Commands', full_name='grpc.CommandList.Commands', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=86,
)


_VALIDATE = _descriptor.Descriptor(
  name='Validate',
  full_name='grpc.Validate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='grpc.Validate.valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=113,
)


_STOP = _descriptor.Descriptor(
  name='Stop',
  full_name='grpc.Stop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Major', full_name='grpc.Stop.Major', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Minor', full_name='grpc.Stop.Minor', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=151,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=160,
)


_ITERATORMESSAGE = _descriptor.Descriptor(
  name='IteratorMessage',
  full_name='grpc.IteratorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='grpc.IteratorMessage.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['CommandList'] = _COMMANDLIST
DESCRIPTOR.message_types_by_name['Validate'] = _VALIDATE
DESCRIPTOR.message_types_by_name['Stop'] = _STOP
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['IteratorMessage'] = _ITERATORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandList = _reflection.GeneratedProtocolMessageType('CommandList', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDLIST,
  '__module__' : 'connector_pb2'
  # @@protoc_insertion_point(class_scope:grpc.CommandList)
  })
_sym_db.RegisterMessage(CommandList)

Validate = _reflection.GeneratedProtocolMessageType('Validate', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATE,
  '__module__' : 'connector_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Validate)
  })
_sym_db.RegisterMessage(Validate)

Stop = _reflection.GeneratedProtocolMessageType('Stop', (_message.Message,), {
  'DESCRIPTOR' : _STOP,
  '__module__' : 'connector_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Stop)
  })
_sym_db.RegisterMessage(Stop)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'connector_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

IteratorMessage = _reflection.GeneratedProtocolMessageType('IteratorMessage', (_message.Message,), {
  'DESCRIPTOR' : _ITERATORMESSAGE,
  '__module__' : 'connector_pb2'
  # @@protoc_insertion_point(class_scope:grpc.IteratorMessage)
  })
_sym_db.RegisterMessage(IteratorMessage)


DESCRIPTOR._options = None

_CONNECTOR = _descriptor.ServiceDescriptor(
  name='Connector',
  full_name='grpc.Connector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=193,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendCommandList',
    full_name='grpc.Connector.SendCommandList',
    index=0,
    containing_service=None,
    input_type=_COMMANDLIST,
    output_type=_VALIDATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendStop',
    full_name='grpc.Connector.SendStop',
    index=1,
    containing_service=None,
    input_type=_STOP,
    output_type=_VALIDATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTOR)

DESCRIPTOR.services_by_name['Connector'] = _CONNECTOR

# @@protoc_insertion_point(module_scope)
